name: Playwright Tests in Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  playwright-run:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.58.2-jammy

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        run: npx playwright test
